
ALTER TABLE APP.SUBASTA
ADD FOREIGN KEY (ID_COMPRADOR_CREADOR) 
REFERENCES APP.COMPRADOR(ID_COMPRADOR);


ALTER TABLE APP.SUBASTA
ADD FOREIGN KEY (ID_PROVEEDOR_GANADOR) 
REFERENCES APP.PROVEEDOR(ID_PROVEEDOR);

ALTER TABLE APP.OFERTADOS
ADD FOREIGN KEY (PRODUCTO_IDPRODUCTO) 
REFERENCES APP.PRODUCTO(ID_PRODUCTO)

ALTER TABLE APP.OFERTADOS
ADD FOREIGN KEY (SUBASTA_IDSUBASTA, SUBASTA_IDCOMPRADORCREADOR) 
REFERENCES APP.SUBASTA(ID_SUBASTA, ID_COMPRADOR_CREADOR);

ALTER TABLE APP.OFERTA
ADD FOREIGN KEY (SUBASTA_IDSUBASTA, SUBASTA_IDCOMPRADORCREADOR) 
REFERENCES APP.SUBASTA(ID_SUBASTA, ID_COMPRADOR_CREADOR);

ALTER TABLE APP.OFERTA
ADD FOREIGN KEY (PROVEEDOR_IDPROVEEDOR) 
REFERENCES APP.PROVEEDOR(ID_PROVEEDOR);